// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateCollection(arg1:string,arg2:string,arg3:string,arg4:number):Promise<models.Collection>;

export function DeleteCollection(arg1:string):Promise<void>;

export function GetCollection(arg1:string):Promise<models.Collection>;

export function ListCollections(arg1:string):Promise<Array<models.Collection>>;

export function UpdateCollection(arg1:string,arg2:string,arg3:any,arg4:number):Promise<models.Collection>;
