// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['CollectionHandler']['CreateCollection'](arg1, arg2, arg3, arg4);
}

export function DeleteCollection(arg1) {
  return window['go']['handlers']['CollectionHandler']['DeleteCollection'](arg1);
}

export function GetCollection(arg1) {
  return window['go']['handlers']['CollectionHandler']['GetCollection'](arg1);
}

export function ListCollections(arg1) {
  return window['go']['handlers']['CollectionHandler']['ListCollections'](arg1);
}

export function UpdateCollection(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['CollectionHandler']['UpdateCollection'](arg1, arg2, arg3, arg4);
}
