// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function ClearCookies():Promise<void>;

export function ListCookies(arg1:string):Promise<Array<services.CookieInfo>>;
