// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateEnvironment(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<models.Environment>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function GetEnvironment(arg1:string):Promise<models.Environment>;

export function ListEnvironments(arg1:string):Promise<Array<models.Environment>>;

export function SetActiveEnvironment(arg1:string,arg2:string):Promise<models.Environment>;

export function UpdateEnvironment(arg1:string,arg2:string,arg3:string):Promise<models.Environment>;
