// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEnvironment(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['EnvironmentHandler']['CreateEnvironment'](arg1, arg2, arg3, arg4);
}

export function DeleteEnvironment(arg1) {
  return window['go']['handlers']['EnvironmentHandler']['DeleteEnvironment'](arg1);
}

export function GetEnvironment(arg1) {
  return window['go']['handlers']['EnvironmentHandler']['GetEnvironment'](arg1);
}

export function ListEnvironments(arg1) {
  return window['go']['handlers']['EnvironmentHandler']['ListEnvironments'](arg1);
}

export function SetActiveEnvironment(arg1, arg2) {
  return window['go']['handlers']['EnvironmentHandler']['SetActiveEnvironment'](arg1, arg2);
}

export function UpdateEnvironment(arg1, arg2, arg3) {
  return window['go']['handlers']['EnvironmentHandler']['UpdateEnvironment'](arg1, arg2, arg3);
}
