// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPostman(arg1, arg2, arg3) {
  return window['go']['handlers']['ExporterHandler']['ExportPostman'](arg1, arg2, arg3);
}

export function ExportSwagger(arg1, arg2, arg3) {
  return window['go']['handlers']['ExporterHandler']['ExportSwagger'](arg1, arg2, arg3);
}
