// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {handlers} from '../models';

export function ClearHistory(arg1:string):Promise<void>;

export function DeleteHistory(arg1:string):Promise<void>;

export function ListHistory(arg1:string,arg2:number):Promise<Array<models.History>>;

export function RecordHistory(arg1:handlers.RecordHistoryInput):Promise<models.History>;
