// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory(arg1) {
  return window['go']['handlers']['HistoryHandler']['ClearHistory'](arg1);
}

export function DeleteHistory(arg1) {
  return window['go']['handlers']['HistoryHandler']['DeleteHistory'](arg1);
}

export function ListHistory(arg1, arg2) {
  return window['go']['handlers']['HistoryHandler']['ListHistory'](arg1, arg2);
}

export function RecordHistory(arg1) {
  return window['go']['handlers']['HistoryHandler']['RecordHistory'](arg1);
}
