// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function ImportCurl(arg1:string):Promise<handlers.ImportRequest>;

export function ImportPostman(arg1:string):Promise<handlers.ImportResponse>;

export function ImportSwagger(arg1:string):Promise<handlers.ImportResponse>;
