// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportCurl(arg1) {
  return window['go']['handlers']['ImporterHandler']['ImportCurl'](arg1);
}

export function ImportPostman(arg1, arg2) {
  return window['go']['handlers']['ImporterHandler']['ImportPostman'](arg1, arg2);
}

export function ImportSwagger(arg1, arg2) {
  return window['go']['handlers']['ImporterHandler']['ImportSwagger'](arg1, arg2);
}
