// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1, arg2) {
  return window['go']['handlers']['ProjectHandler']['CreateProject'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['handlers']['ProjectHandler']['DeleteProject'](arg1);
}

export function GetProject(arg1) {
  return window['go']['handlers']['ProjectHandler']['GetProject'](arg1);
}

export function ListProjects() {
  return window['go']['handlers']['ProjectHandler']['ListProjects']();
}

export function UpdateProject(arg1, arg2, arg3) {
  return window['go']['handlers']['ProjectHandler']['UpdateProject'](arg1, arg2, arg3);
}
