// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {handlers} from '../models';
import {httpclient} from '../models';

export function CreateRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:number):Promise<models.Request>;

export function DeleteRequest(arg1:string):Promise<void>;

export function GetRequest(arg1:string):Promise<models.Request>;

export function ListRequests(arg1:string):Promise<Array<models.Request>>;

export function SendRequest(arg1:handlers.SendRequestInput):Promise<httpclient.Response>;

export function UpdateRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:number):Promise<models.Request>;
