// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRequest(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['handlers']['RequestHandler']['CreateRequest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function DeleteRequest(arg1) {
  return window['go']['handlers']['RequestHandler']['DeleteRequest'](arg1);
}

export function GenerateCode(arg1, arg2) {
  return window['go']['handlers']['RequestHandler']['GenerateCode'](arg1, arg2);
}

export function GetRequest(arg1) {
  return window['go']['handlers']['RequestHandler']['GetRequest'](arg1);
}

export function ListRequests(arg1) {
  return window['go']['handlers']['RequestHandler']['ListRequests'](arg1);
}

export function ListRequestsByProject(arg1) {
  return window['go']['handlers']['RequestHandler']['ListRequestsByProject'](arg1);
}

export function RunAsserts(arg1) {
  return window['go']['handlers']['RequestHandler']['RunAsserts'](arg1);
}

export function SendRequest(arg1) {
  return window['go']['handlers']['RequestHandler']['SendRequest'](arg1);
}

export function UpdateRequest(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['handlers']['RequestHandler']['UpdateRequest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}
