// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['handlers']['WebSocketHandler']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['handlers']['WebSocketHandler']['Disconnect']();
}

export function IsConnected() {
  return window['go']['handlers']['WebSocketHandler']['IsConnected']();
}

export function Send(arg1) {
  return window['go']['handlers']['WebSocketHandler']['Send'](arg1);
}

export function SetContext(arg1) {
  return window['go']['handlers']['WebSocketHandler']['SetContext'](arg1);
}
