// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Connect(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function IsConnected():Promise<boolean>;

export function Send(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
