// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function ActivateEnvironment(arg1:number):Promise<void>;

export function CancelRequest(arg1:number):Promise<void>;

export function ClearHistory(arg1:number):Promise<void>;

export function CloneRequest(arg1:number):Promise<models.Request>;

export function CreateCollection(arg1:number,arg2:any,arg3:string):Promise<models.Collection>;

export function CreateEnvironment(arg1:number,arg2:string,arg3:any):Promise<models.Environment>;

export function CreateProject(arg1:string,arg2:string):Promise<models.Project>;

export function CreateRequest(arg1:number,arg2:string,arg3:string):Promise<models.Request>;

export function DeleteCollection(arg1:number):Promise<void>;

export function DeleteEnvironment(arg1:number):Promise<void>;

export function DeleteHistory(arg1:number):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteRequest(arg1:number):Promise<void>;

export function ExportPostman(arg1:number):Promise<string>;

export function GenerateDocsHTML(arg1:number):Promise<string>;

export function GenerateDocsMarkdown(arg1:number):Promise<string>;

export function GetAllSettings():Promise<Record<string, string>>;

export function GetCollectionTree(arg1:number):Promise<Array<models.TreeItem>>;

export function GetProject(arg1:number):Promise<models.Project>;

export function GetRequest(arg1:number):Promise<models.Request>;

export function GetSetting(arg1:string):Promise<string>;

export function ImportPostman(arg1:number,arg2:string):Promise<services.ImportResult>;

export function ListEnvVariables(arg1:number):Promise<Array<models.EnvVariable>>;

export function ListEnvironments(arg1:number):Promise<Array<models.Environment>>;

export function ListHistory(arg1:number,arg2:number,arg3:number):Promise<Array<models.History>>;

export function ListProjects():Promise<Array<models.Project>>;

export function MoveCollection(arg1:number,arg2:any,arg3:number):Promise<void>;

export function RenameCollection(arg1:number,arg2:string):Promise<void>;

export function RenameEnvironment(arg1:number,arg2:string):Promise<void>;

export function ResolveVariable(arg1:string,arg2:number):Promise<string>;

export function ResolveVariableMap(arg1:Record<string, string>,arg2:number):Promise<Record<string, string>>;

export function SaveEnvVariables(arg1:number,arg2:Array<models.EnvVariable>):Promise<void>;

export function SearchHistory(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:number):Promise<Array<models.History>>;

export function SendQuickRequest(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<models.HTTPResponse>;

export function SendRequest(arg1:number,arg2:models.Request,arg3:number):Promise<models.HTTPResponse>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function UpdateProject(arg1:number,arg2:string,arg3:string):Promise<models.Project>;

export function UpdateRequest(arg1:models.Request):Promise<void>;

export function WSConnect(arg1:string,arg2:string):Promise<void>;

export function WSDisconnect(arg1:string):Promise<void>;

export function WSSend(arg1:string,arg2:string):Promise<void>;
