// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateEnvironment(arg1) {
  return window['go']['main']['App']['ActivateEnvironment'](arg1);
}

export function CancelRequest(arg1) {
  return window['go']['main']['App']['CancelRequest'](arg1);
}

export function ClearHistory(arg1) {
  return window['go']['main']['App']['ClearHistory'](arg1);
}

export function CloneRequest(arg1) {
  return window['go']['main']['App']['CloneRequest'](arg1);
}

export function CreateCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2, arg3);
}

export function CreateEnvironment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateEnvironment'](arg1, arg2, arg3, arg4);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreateRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateRequest'](arg1, arg2, arg3);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteRequest(arg1) {
  return window['go']['main']['App']['DeleteRequest'](arg1);
}

export function ExportPostman(arg1) {
  return window['go']['main']['App']['ExportPostman'](arg1);
}

export function GenerateDocsHTML(arg1) {
  return window['go']['main']['App']['GenerateDocsHTML'](arg1);
}

export function GenerateDocsMarkdown(arg1) {
  return window['go']['main']['App']['GenerateDocsMarkdown'](arg1);
}

export function GenerateRequestDocsHTML(arg1) {
  return window['go']['main']['App']['GenerateRequestDocsHTML'](arg1);
}

export function GenerateRequestDocsMarkdown(arg1) {
  return window['go']['main']['App']['GenerateRequestDocsMarkdown'](arg1);
}

export function GetAllSettings() {
  return window['go']['main']['App']['GetAllSettings']();
}

export function GetCollectionTree(arg1) {
  return window['go']['main']['App']['GetCollectionTree'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjectStats(arg1) {
  return window['go']['main']['App']['GetProjectStats'](arg1);
}

export function GetRequest(arg1) {
  return window['go']['main']['App']['GetRequest'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function ImportPostman(arg1, arg2) {
  return window['go']['main']['App']['ImportPostman'](arg1, arg2);
}

export function ListEnvVariables(arg1) {
  return window['go']['main']['App']['ListEnvVariables'](arg1);
}

export function ListEnvironments(arg1) {
  return window['go']['main']['App']['ListEnvironments'](arg1);
}

export function ListHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListHistory'](arg1, arg2, arg3);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function MoveCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveCollection'](arg1, arg2, arg3);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function RenameEnvironment(arg1, arg2) {
  return window['go']['main']['App']['RenameEnvironment'](arg1, arg2);
}

export function ResolveVariable(arg1, arg2) {
  return window['go']['main']['App']['ResolveVariable'](arg1, arg2);
}

export function ResolveVariableMap(arg1, arg2) {
  return window['go']['main']['App']['ResolveVariableMap'](arg1, arg2);
}

export function SaveEnvBaseURL(arg1, arg2) {
  return window['go']['main']['App']['SaveEnvBaseURL'](arg1, arg2);
}

export function SaveEnvVariables(arg1, arg2) {
  return window['go']['main']['App']['SaveEnvVariables'](arg1, arg2);
}

export function SearchHistory(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SearchHistory'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SendQuickRequest(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SendQuickRequest'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SendRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2, arg3);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function UpdateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3);
}

export function UpdateRequest(arg1) {
  return window['go']['main']['App']['UpdateRequest'](arg1);
}

export function WSConnect(arg1, arg2) {
  return window['go']['main']['App']['WSConnect'](arg1, arg2);
}

export function WSDisconnect(arg1) {
  return window['go']['main']['App']['WSDisconnect'](arg1);
}

export function WSSend(arg1, arg2) {
  return window['go']['main']['App']['WSSend'](arg1, arg2);
}
